CREATE DATABASE PTDAPM_N3;
-- Bảng Tài khoản
CREATE TABLE TAI_KHOAN (
    EMAIL VARCHAR(100) PRIMARY KEY NOT NULL,
    MAT_KHAU VARCHAR(255) NOT NULL
);

-- Bảng Giảng viên
CREATE TABLE GIANG_VIEN (
    MA_GV VARCHAR(20) PRIMARY KEY NOT NULL,
    HO_TEN VARCHAR(100) NOT NULL,
    KHOA VARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    SO_LUONG_SINH_VIEN_HUONG_DAN INT DEFAULT 0
);

-- Bảng Văn phòng khoa
CREATE TABLE VAN_PHONG_KHOA (
    MA_NV VARCHAR(20) PRIMARY KEY NOT NULL,
    HO_TEN VARCHAR(100) NOT NULL,
    CHUC_VU VARCHAR(100) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL
);

-- Bảng Doanh nghiệp
CREATE TABLE DOANH_NGHIEP (
    MA_DN VARCHAR(20) PRIMARY KEY NOT NULL,
    TEN_DN VARCHAR(255) NOT NULL,
    DIA_CHI TEXT NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    NGUOI_LIEN_HE VARCHAR(100) NOT NULL,
    SO_LUONG_SINH_VIEN_TIEP INT DEFAULT 0
);

-- Bảng Sinh viên
CREATE TABLE SINH_VIEN (
    MA_SV VARCHAR(20) PRIMARY KEY NOT NULL,
    HO_TEN VARCHAR(100) NOT NULL,
    NGAY_SINH DATE NOT NULL,
    GIOI_TINH ENUM('Nam', 'Nữ') NOT NULL,
    LOP VARCHAR(20) NOT NULL,
    SDT VARCHAR(15) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    DIA_CHI TEXT NOT NULL,
    MA_GV VARCHAR(20),
    MA_DN VARCHAR(20),
    FOREIGN KEY (MA_GV) REFERENCES GIANG_VIEN(MA_GV),
    FOREIGN KEY (MA_DN) REFERENCES DOANH_NGHIEP(MA_DN)
);

-- Bảng Đồ án
CREATE TABLE DO_AN (
    MA_DO_AN VARCHAR(20) PRIMARY KEY UNIQUE NOT NULL,
    TIEU_DE VARCHAR(255) NOT NULL,
    MO_TA TEXT NULL,
    THOI_GIAN_BAT_DAU DATE NOT NULL,
    THOI_GIAN_KET_THUC DATE NOT NULL,
    MA_SV VARCHAR(20),
    MA_GV VARCHAR(20),
    MA_DN VARCHAR(20),
    TRANG_THAI ENUM('Chưa hoàn thành', 'Hoàn thành') NOT NULL,
    DIEM_SO FLOAT DEFAULT NULL,
    FOREIGN KEY (MA_SV) REFERENCES SINH_VIEN(MA_SV),
    FOREIGN KEY (MA_GV) REFERENCES GIANG_VIEN(MA_GV),
    FOREIGN KEY (MA_DN) REFERENCES DOANH_NGHIEP(MA_DN)
);

-- Bảng Báo cáo đồ án
CREATE TABLE BAO_CAO_DO_AN (
    MA_BAO_CAO INT PRIMARY KEY AUTO_INCREMENT,
    TIEU_DE VARCHAR(255) NOT NULL,
    NOI_DUNG TEXT NOT NULL,
    MA_DO_AN VARCHAR(20),
    NGUOI_TAO VARCHAR(255) NOT NULL,
    NGAY_TAO DATE NOT NULL,
    TRANG_THAI ENUM('Chờ duyệt', 'Đã duyệt', 'Bị từ chối') DEFAULT 'Chờ duyệt',
    FOREIGN KEY (MA_DO_AN) REFERENCES DO_AN(MA_DO_AN)
);

-- Bảng Nhận xét báo cáo
CREATE TABLE NHAN_XET_BAO_CAO (
    MA_NHAN_XET INT PRIMARY KEY AUTO_INCREMENT,
    MA_BAO_CAO INT,
    MA_GV VARCHAR(20),
    NOI_DUNG TEXT NOT NULL,
    MA_DN VARCHAR(20),
    NHAN_XET TEXT NOT NULL,
    FOREIGN KEY (MA_BAO_CAO) REFERENCES BAO_CAO_DO_AN(MA_BAO_CAO),
    FOREIGN KEY (MA_GV) REFERENCES GIANG_VIEN(MA_GV),
    FOREIGN KEY (MA_DN) REFERENCES DOANH_NGHIEP(MA_DN)
);

-- Bảng Lịch bảo vệ đồ án
CREATE TABLE LICH_BAO_VE (
    MA_LICH INT PRIMARY KEY AUTO_INCREMENT,
    MA_DO_AN VARCHAR(20),
    NGAY_GIO DATETIME NOT NULL,
    DIA_DIEM VARCHAR(255) NOT NULL,
    MA_GIAM_KHAO VARCHAR(20),
    FOREIGN KEY (MA_DO_AN) REFERENCES DO_AN(MA_DO_AN),
    FOREIGN KEY (MA_GIAM_KHAO) REFERENCES GIANG_VIEN(MA_GV)
);

-- Bảng Kết quả thực tập
CREATE TABLE KET_QUA_THUC_TAP (
    MA_KET_QUA VARCHAR(20) PRIMARY KEY UNIQUE NOT NULL,
    MA_SV VARCHAR(20),
    MA_DN VARCHAR(20),
    MA_GV VARCHAR(20),
    MA_DO_AN VARCHAR(20),
    DIEM_SO FLOAT DEFAULT NULL,
    NHAN_XET_CUA_GIANG_VIEN TEXT NULL,
    NHAN_XET_CUA_DOANH_NGHIEP TEXT NULL,
    FOREIGN KEY (MA_SV) REFERENCES SINH_VIEN(MA_SV),
    FOREIGN KEY (MA_DN) REFERENCES DOANH_NGHIEP(MA_DN),
    FOREIGN KEY (MA_GV) REFERENCES GIANG_VIEN(MA_GV),
    FOREIGN KEY (MA_DO_AN) REFERENCES DO_AN(MA_DO_AN)
);
ALTER TABLE do_an MODIFY trang_thai ENUM('Chưa có đề tài', 'Chưa hoàn thành', 'Hoàn thành','Đang mở','Đóng') NOT NULL;
-- Cập nhật cột ngay_sinh, sdt, dia_chi có thể NULL
ALTER TABLE SINH_VIEN 
MODIFY NGAY_SINH DATE NULL,
MODIFY SDT VARCHAR(15) NULL,
MODIFY DIA_CHI VARCHAR(255) NULL;

-- Cập nhật cột gioi_tinh mặc định là 'Nam'
ALTER TABLE SINH_VIEN 
MODIFY GIOI_TINH VARCHAR(10) DEFAULT 'Nam' NOT NULL;
